name: Run Python Script

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium telethon python-dotenv
          
      - name: Install Edge browser and driver
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
          sudo apt update
          sudo apt install microsoft-edge-stable
          wget https://msedgedriver.azureedge.net/133.0.3065.92/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/msedgedriver

      - name: Install gdown
        run: |
          pip install gdown
          
      - name: Download and extract Edge profile
        run: |
          pip install gdown
          gdown "https://drive.google.com/uc?export=download&id=1dGF2sY52HQFMwIxR17Ve7ieCilyjncyb" -O Default.zip
          mkdir -p /home/runner/.config/microsoft-edge-${{ github.run_id }}/Default
          unzip Default.zip -d /home/runner/.config/microsoft-edge-${{ github.run_id }}/Default

      - name: List profile directory contents
        run: |
          ls -l /home/runner/.config/microsoft-edge-${{ github.run_id }}/Default
        
      - name: Run Python script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          EDGE_DRIVER_PATH: /usr/local/bin/msedgedriver
          EDGE_USER_DATA_DIR_PATH: /home/runner/.config/microsoft-edge-${{ github.run_id }}
          EDGE_PROFILE_DIR: Default
        run: |
          mkdir -p $EDGE_USER_DATA_DIR_PATH
          python main.py

      - name: Clean up user data directory
        run: |
          rm -rf /home/runner/.config/microsoft-edge-${{ github.run_id }}

